apiVersion: v1
kind: Service
metadata:
  namespace: sd
  name: app-sd-node-port-service
spec:
  ports:
      # service port in cluster
    - port: 8080
      # port to contact inside container
      targetPort: 8080
  selector:
    app: app-sd
  type: NodePort