apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sd-mongo-pv-claim
  namespace: sd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi