apiVersion: v1
kind: Service
metadata:
  namespace: sd
  name: sd-mongo-cluster-ip-service
spec:
  ports:
      # service port in cluster
    - port: 27017
      # port to contact inside container
      targetPort: 27017
  selector:
    app: sd-mongo
  type: NodePort
 